### PR TITLE
Catalyst: Settings are a separate window + sidebar search icon is now a searchbar

### PR DESCRIPTION
**Pull request by Schlaubischlump**
As previously discussed, I've completed the updates for both the search bar and the settings. To ensure the settings window behaves correctly, I incorporated some AppKit code, which I’ve isolated into a separate bundle that is only embedded in macOS.

Searchbar: 

Screenshot 2024-08-18 at 14 31 48

Settings: 

Screenshot 2024-08-18 at 14 36 06

While I believe the code could still benefit from some cleanup, I wanted to submit the pull request before my vacation ends. If you want me to change anything or restructure the code somewhere let me know!

### CODE REVIEW

**Comment by BLeeEZ** [comment]
First of all thank you very much for your work. It looks really good. I am currently performing the code review. One question: Why is there a new package called AppKitIntegration? Is it possible to add this functionality in Amperfy project or is it strictly required to do that in a separate package?

**Comment by Schlaubischlump** [comment]
The `AppKitController` class in the package directly imports `AppKit`. To my knowledge that is not possible if you add it directly to the Amperfy project, which uses UIKit. If you want to add the functionally directly to the Amperfy project you need to rewrite the code to not use `AppKit`. In particular that means, you need to access every `AppKit` class with `NSClassFromString` and use `perfrom` to call a function.

**Comment by BLeeEZ** [comment]
I noticed two things during testing:
- Settings -> Sever -> Manage Server URLs -> „+“: The view is bigger then the hosting settings window
- Menu Bar -> View -> Show All Tabs -> „+“: This leads to an App crash

**Comment by Schlaubischlump** [comment]
1. Yes, I noticed this as well if you are referring to the sheets and alerts. I looked for workarounds, but the only solution that would work is wrapping the UIKit API for sheets / alerts ourselves and expose it to SwiftUI. I did not do this, because I didn't want to make the pull request larger. However, I can have a look and try to implement something to work around this. 

2. I can not reproduce this. The settings window does not show the tabbar option (I disabled that), so I assume you are talking about the main window, right?

**Comment by BLeeEZ** [comment]
1. for now it is OK. Especially that it is a window you only see once in a while.
2. Yes this occurs in Main window. I think this is not related to this PR. This needs to be handled separately. Either by removing only the „Show All Tabs“ or the complete „View“ menu item or fixing the underlying crash. 

I will do a small adjustments commit and then this PR can be completed.

**Comment by BLeeEZ** [comment]
Thanks again for this great work.

**Pull request merged**
