### PR TITLE
feature: Add small widget

### PR DESCRIPTION
**Pull request by danielepintore**
Hi, in this pull request I've added a widget like the one that is on the apple music app. The widget is simple it displays the song artwork, the song name and the artist name. There is a button that allows to start/stop the playback. Everything should be fine, but i think you should adjust the xcode project file with the correct developer account for the widget extension. Keep in mind that an app group should also be created.
Here are some screenshots of the widget:
image
image

### CODE REVIEW

**Comment by BLeeEZ** [comment]
Hi,
first of all thank you for the provided code.
I am currently on a business trip and not able to do a proper testing.

Just some remarks:
- I was happy to remove the last extension that was handling the SiriShortcuts. These extensions are difficult to handle and difficult to debug. I was able to handle SiriShortcuts as InAppIntentes. I don't know if this possible to Widgets too.
- I am not happy to introduce App Groups. A second place where data is stored is error prone. 
- Currently playing song and player status is stored in CoreData. This widget approach needs to store the same information in two different places (UserDefaults and CoreData), which is again error prone.

**Comment by danielepintore** [comment]
Understood, I think that the extension is required for a widget, but i can try to remove the app group requirement and change the method to retrieve data.

**Comment by TheFireRed** [comment]
Amperfy is great and I think the only feature I’m missing is a widget so I’m delighted this is in development. Are there going to be multiple sizes for it, like Spotify and Deezer have? 

image

**Comment by danielepintore** [comment]
I'll make a new pull request once I've fixed the issues. Since I'm unsure when I'll have time to work on it, I'll close this one for now.

**Pull request closed without merging**
