### PR TITLE
feat: Add an option to sort with starred date in the favorite songs section

### PR DESCRIPTION
**Pull request by danielepintore**
This pull request adds the option to sort songs in the "Favorite songs" section by their starred date. I think that this is useful in order to keep track of recent favorite songs. This feature will make the "Favorite songs" section work like Spotify one.

In order to keep the modification available only in the favorite section i have created a new `UserDefaultsKey` called `favoriteSortSetting` just for storing the preferred way to sort only in the favorite section.

I've implemented only for Subsonic server since i don't know if Ampache ones have this.
Edit: I have also created a new model version that includes the `starredDate` variable for `AbstractLibraryEntity`. I've choose to add this property in this object because even artists and album can be marked as starred.

### CODE REVIEW

**Comment by BLeeEZ** [comment]
Thank you for this feature. There are some things missing to complete this feature:

- unit tests for the subsonic parser
- favourite sort option used in CarPlay too
- Ampache 

Besides that it already looks really good.

**Comment by BLeeEZ** [comment]
I take care over these points.

**Comment by danielepintore** [comment]
Thanks 👍🏻

**Comment by BLeeEZ** [comment]
Points are now completed. Thank you for your implementation.

**Pull request merged**
