### PR TITLE
Restore window size on macOS

### PR DESCRIPTION
**Pull request by Schlaubischlump**
@BLeeEZ this patch should restore the window size on macOS (regardless of the settings we discussed in the issue). Can you check if it works for you as well?

### CODE REVIEW

**Comment by BLeeEZ** [comment]
Thank you for this PR. The window size now saved when the Amperfy is closed completely (Menu Bar -> Quit Amperfy). The window size is not saved when closed via the red "x" button.

**Comment by Schlaubischlump** [comment]
I think that is the default behavior for all mac apps, isn't it?

**Comment by BLeeEZ** [comment]
At least all Apple macOS keep their position and window size when closing via red "x".

**Comment by BLeeEZ** [comment]
Sorry to keep this PR open for so long but I needed to finish publishing v1.2.2.

**Comment by Schlaubischlump** [comment]
No worries. 

I tried to find a way to also keep the window size open after closing with the red x. Currently I haven't found a nice solution. If I do, I'll open a new pull request.

**Pull request merged**
