### PR TITLE
MacOS Player controls

### PR DESCRIPTION
**Pull request by Schlaubischlump**
Features:
- New player controls for macOS in the main window's toolbar (including a "..." menu when you hover the song title)
- New mini player activated by clicking on the artwork in the toolbar
- New menubar actions to control the playback
- New filter icon in all secondary views
- New slide over menu for music player queue and live lyrics

Bug fixes:
- Fix incorrectly sized sheets in the settings window (e.g. Update password sheet)
- Fix the searchfield in the sidebar, which stole the focus of all other searchfields
- Fix various small bugs when multiple tabs are opened (Note: each tab has its own window scene. The appDelegate.window trick does not work anymore with more than one scene. We should probably remove this in the future)
- Fix display errors in the queue view on macOS by forcing a compact layout
- Fix window title is not updated correctly
- Fix switching a tab in settings enables the Full-Screen button of the window
- Fix settings window has wrong background color on macOS
- Fix GenreDetailVC and DictionaryVC are laggy while scrolling on macOS (Maybe related to #310?)
- Fix support for macOS 13.X

Removed:
- Remove the popup player in the sidebar
 
To be tested: 
- The iOS version (I think I didn't break anything)
- MacOS: The podcast view (I don't have podcasts in my library)
- MacOS: Live lyrics (I don't have any)
- MacOS: 12.X  
    - Untested: Probably won't work or look bad, because it does not support `UIBehavioralStyle.mac` for `UINavigationBar`

### CODE REVIEW

**Comment by BLeeEZ** [comment]
Thank you very much again. Your work is highly appreciated.
I currently have no debug environment at hand. I can start testing at mid of September.

**Comment by Schlaubischlump** [comment]
No worries, take your time :)

**Comment by Schlaubischlump** [comment]
I have finished a first draft for the slide-over menu. Sadly, the Queue view required a lot of code duplication. Maybe we can refactor that in the future. I think the macOS version is now in a good state where it is ready to be shipped when all the bugs are fixed.

Screenshot 2024-09-01 at 01 10 32
Screenshot 2024-09-01 at 01 10 39

**Comment by Schlaubischlump** [comment]
@BLeeEZ just wanted to let you know that I keep the first message updated whenever I change something. 

I tested macOS 13.X and applied some fixes. It seems to be fully working now. I don't know if 12.X works at and how it looks like. The problem is, that one needs to support macOS 12.X when you support iOS 15. Maybe we add a popup message for macOS 11.X with a warning that it is untested?

**Comment by BLeeEZ** [comment]
I am currently testing and review the PR and I must say this PR is awesome.
It works really well and looks amazing.

**Comment by Schlaubischlump** [comment]
Glad that you like it :)

**Comment by BLeeEZ** [comment]
Do you have any other open points?
Otherwise I would begin with the merge of this PR.

PS: one improvement ideas, that does not need to be included here, is to add elapsed time and remaining time to the macOS NowPlayingBarItem when the user hovers over.

**Comment by Schlaubischlump** [comment]
No other open points. I think I addressed everything I wanted to address. You can begin merging :) 

Right, I wanted to add that but somehow forgot about it. I might add it in an additional pull request, whenever I find the time to implement it.

**Pull request merged**
