### PR TITLE
Settings: limit cache size (excluding Artworks)

### LINKED ISSUE #170: [Feature request] Limit size of cache
Hi, thanks for your work, using your app daily.

It would be nice to limit the size of the cache, because currently all the free space available is used, and I need to free some space up occasionally which means I need to clear the whole cache within amperfy.

### PR DESCRIPTION
**Pull request by f-longobardi**
resolves #170

### CODE REVIEW

**Comment by BLeeEZ** [comment]
First of all thank you very much for your contribution. I appreciate it. I will need some time to check for the changes, since I am currently quite busy. First look is good.

**Comment by BLeeEZ** [comment]
Your work is really good. Do you confirm with my small adjustments?

**Review by f-longobardi — COMMENTED** [review]
LGTM! Thank you!

about the style guide do you have a reference somewhere?

**Comment by BLeeEZ** [comment]
I have no specific reference, sorry.

**Pull request merged**
