### PR TITLE
Catalyst support

### PR DESCRIPTION
**Pull request by Schlaubischlump**
This pull requests adds support for macOS Catalyst. Sadly I could only test it on macOS 14.5, but it should work with macOS 12.x and 13.x as well. 

I had to change the reordering mechanism in `LibraryNavigationConfigurator` slightly. I now use `dataSource.reorderingHandlers` (supported since iOS 14). This simplifies the code, but more importantly, it fixes reordering the sidebar on Catalyst. Otherwise, the app will just crash. There are some weird bugs in Catalyst that one has to work around and, worst of all, none of them are documented. Another example is `UIDeferredMenuElement` which is supported in Catalyst but never triggers the handler to update the menu and as such is stuck on `Loading...`. 

Unrelated changes, that I can remove if you don't like them: 
- I changed the full screen slider popup for changing the album artwork size to a less intrusive popup that is attached to the menu button (this applies to iOS and iPad OS as well). You still open it with the same menu item as before.
Screenshot 2024-08-03 at 22 56 33    

- I added a Pink theme that matches the native Music App. 

Let me know if I should change anything.

### CODE REVIEW

**Comment by BLeeEZ** [comment]
Thank you very much for your work. I will need some time time for testing and reviewing.

**Comment by rudolphmax** [comment]
I am super interested in this feature. Let me know if there is anything else to do here. I'd be happy to help!

**Comment by BLeeEZ** [comment]
@rudolphmax when this PR is merged some improvements can be done. I think an embedded player on top line the Apple Music MacOs app would be nice. 

@Schlaubischlump really great work, thank you. I am currently doing some adjustments to this PR to fix some design topics.

**Comment by rudolphmax** [comment]
@BLeeEZ right, I'll keep my eyes peeled then. I have noticed some details that might need addressing as well, you might be on to those already, though.

**Comment by BLeeEZ** [comment]
@Schlaubischlump great idea to bind the "album collection size slider" popover to the options button instead of showing it centred in the view. It looks much nicer.

**Comment by Schlaubischlump** [comment]
Glad that you like it :)

**Comment by BLeeEZ** [comment]
I finished code review and fixed some minor issues. 
I am now merging this PR to master.
@Schlaubischlump Thanks again for this great port.

**Comment by Schlaubischlump** [comment]
Great to hear!

**Pull request merged**
